
# Grants

<!-- ```{r grant, eval = FALSE}
vroom::vroom("data/grant.csv") %>%
  tidyr::fill(-why) %>%
  vitae::detailed_entries(what, when, with, where, why)
``` -->

## Submitted Grants

- "Development of an AI-Powered Multimodal Cognitive Assessment System for Blind and Low-Vision Individuals," Co-I, National Institutes on Disability, Independent Living, and Rehabilitation Research (NIDILRR), HHS-2025-ACL-NIDILRR-IFDV-0105, $699,559, 2025-2029 (submitted). PI: Choi, S.; Co-Is: Seo, J. and Rizzo, JR.


## Awarded Grants

- "Collaborative Research: An AudioTactile Data System for Blind or Low Vision Faculty, Staff, Postdocs, and Graduate Students in Chemistry, Math, Computer and Information Sciences," PI (at UIUC), National Science Foundation (NSF Grant Award #2348166),  Workplace Equity for Persons with Disabilities in STEM and STEM Education (nsf23593), $459,000 (for UIUC) out of $1,200,159 total, August 2024 - July 2028 (ongoing).

- "Beyond Visuals: Improving Accessibility of Data Curation and Multi-Modal Representations for People of all Abilities through Reproducible Workflows," PI, Institute of Museum and Library Services (IMLS) Laura Bush 21st Century Librarian Program, Grant #RE-254891-OLS-23, $649,921, Aug 2023 - July 2026 (early terminated on April 28th, 2025 affected by the President’s Executive Order 14238).

- "Promoting Computational Thinking Skills for Blind and Visually Impaired Teens through Accessible Library Makerspaces," PI, Institute of Museum and Library Services (IMLS) National Leadership Grants, Grant #LG-252360-OLS-22, $498,638, Aug 2022 - May 2025 (early terminated on April 8th, 2025 affected by the President’s Executive Order 14238).

- "Inclusive Data Science: Fostering Accessibility and Reproducibility with Multimodal Learning Strategies," PI, Teach Access Faculty Grants, Tier 3, $5,000, May 2023 - May 2024 (completed).

- "Improving Accessible Reproducibility for Data Science Publishing System," PI, Posit PBC (unrestricted gift), $54,327, May 2022 - Present (ongoing).

- "Co-designing an Alexa-Based Conversational mHealth System with Visually Impaired People to Promote Physical Activities," Co-PI, Center on Health, Aging, and Disability’s (CHAD) Pilot Grant Program at the University of Illinois at Urbana-Champaign, $29,866, 2023-2024 (ongoing).

- "Category I: Crossing the Divide Between Today's Practice and Tomorrow's Science," Senior Personnel, National Science Foundation (NSF), Grant #2005572, $10,000,000.00, Oct 2021 - Sept 30, 2026 (.5 FTE academic year) (ongoing).

- "Insight without Sight: Enhancing Data Literacy through Multimodal Data Science Education - Smith-Kettlewell Summer Institute," Subaward PI, Rehabilitation Engineering Research Centers (RERC) Program: RERC on Blindness and Low Vision, National Institute on Disability, Independent Living, and Rehabilitation Research (NIDILRR), Grant #90REGE0018-01-00, $11,975, July 17, 2023 - August 11, 2023 (completed).

- "Data Accessibilization: Making Data Science Education Accessible for Blind Learners," PI, Wallace Foundation, Emerging Scholars Program, International Society of the Learning Sciences, $10,000, Jan 2022 - Dec 2022 (completed).

<!-- ## Under-Review Grants -->

<!-- Human Factors and Ergonomics Society’s Diversity & Inclusion Seed Grant Program, $5,000 [Submitted], 2025-2026, Title: Making Medical Imaging Information Accessible for Blind and Low-Vision Individuals from Diverse and Underserved Backgrounds, Choi, S. (PI), Seo, J. (Co-PI)., Pitcher-Cooper, C. (Co-I). -->

<!-- ## Unawarded Projects

- "Multimodal Data Representations Using Generative AI with, by, and for Blind and Low-Vision People," PI, Google Research: Award for Inclusion Research Program, $60,000, August 2023 - July 2024 (unawarded).

- "Developing an Accessible Mobile Food Tracking Application With and For Blind People," Co-PI, National Institute on Disability, Independent Living, and Rehabilitation Research, HHS-2023-ACL-NIDILRR-IFDV-0000, $600,000 (UIUC: $180,000), 2023-2026 (unawarded).

- "Whole Tale Accessibility Project," Co-PI, The Sloan Foundation, Submitted for Aug 2022 - Aug 2023, $225,000 (unawarded).

- "Understanding the Sleep Patterns of Blind Populations Using Self-Tracking Technologies - What is It Like and How can We Support It?", Co-PI, The Center on Health, Aging, and Disability, College of Applied Health Sciences, Submitted for July 2022 - December 2023, $30,000 (unawarded). -->
