---
output:
  word_document:
    reference_docx: "C:/Users/sjysk/OneDrive/Desktop/Seo_dissertation_2020-05-27.docx"
    # pandoc_args:
      # - --lua-filter="../lua/strong.lua"
# csl: "../csl/apa6-cv.csl"
# bibliography: selected.bib
# nocite: "@*"
---

I would first like to acknowledge that this study was supported by the Dissertation Research Initiation Grant by the College of Education at the Pennsylvania State University (fund #1001). The findings, opinions and recommendations herein do not necessarily reflect the NFB nor Pennsylvania State University. I would like to thank the National Federation of the Blind and the members who generously shared their collective wisdom, experience, and materials for the purposes of this research.

With heartfelt and deepest gratitude, I acknowledge the excellent support from my advisor, Dr. Gabriela T. Richard, in completing this dissertation. Her warm encouragement and insightful advice truly guided me throughout my Ph.D. journey at Penn State. My dissertation would not have happened without her warmest support.

I am extremely grateful my dissertation committee members, Dr. Roy B. Clariana, Dr. ChanMin Kim, and Dr. Mary Beth Rosson for their critical feedback and insightful discussion. Their insightful and constructive comments pushed me to sharpen my thinking and brought my work to a higher level.

I would like to acknowledge my colleagues in Learning, design, and Technology for their wonderful collaboration and lovely support. My special thanks go to my academic brothers and sisters--Josh Gi Woong Choi, Soo Hyeon Kim, Yong Ju Jung, Eunsung Park, and Hye Yeon Lee. Without their unconditional help, I would not have been able to make it this far. I also would like to thank my colleagues at Dr. Richard's Playful Learning and Inclusive Design Research Group for their wonderful friendship. Sagun Giri, Zachary McKinley, and R. William Ashley, all of you will be missed and remembered.

In addition, I would like to express my sincere gratitude to people who fostered a more accessible learning environment at Penn State. Susan Hayya, Christian Vinten-Johansen, Jamilyn Houser, Elizabeth Pyatt, Mona AlQahtani, Deborah Austin, Philip Voorhees, Michelle McManus, Natalie Harrison, Tanner Zaffuto, and Sonya Woods--they all have been always with me to push Penn State towards a more inclusive institution for people with and without dis/abilities.

Especially, I would like to thank my parents, sisters, and all my family members in Korea for their endless love. Even though my Ph.D. journey was long and lonely, I could get through because of their continuous prayers and unconditional support.

Last but not least, from the bottom of my heart I would like to say big thank  my Fiancé and wonderful colleague, Soyoung Choi, for being my lovely friend and biggest supporter throughout my dissertation work. Without her extensive help, this work would not have been possible. Also, I would like to sincerely thank my guide dog, Arang, for being my closest friend and being my eyes for me to complete this long Ph.D. journey. Arang, you also deserve the Ph.D. degree!
